# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Vigo 2017"
email: "info@gdgvigo.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/devfest.gdgvigo.com"
url: "https://gdgspain.github.io/devfest.gdgvigo.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Vigo"
organizerAlternateName: "Google Developer Group Vigo"
organizerDescription: "Open and volunteer geek community who create exciting projects and share experience about Google technology with passion."
organizerEmail: "info@gdgvigo.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://developers.google.com/groups/chapter/106284181570326060854/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, vigo"
twitterAccount: "@GDGVigo"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 #- {permalink: "/schedule/", text: "Schedule"}
 #- {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Location"}
 #- {permalink: "/firebase-appfest/", text: "Firebase Appfest"}
bottomNavigationLinks:
 - {link: "https://gdgvigo.typeform.com/to/JvDH2h", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://gdgvigo.typeform.com/to/JvDH2h", text: "Become a speaker"}

# Hero Block
heroImage: "fireworks.jpg"
heroTitle: "GDG DevFest <typeout> 2017"
eventDate: "Octubre, 2017"
typeoutTextValues: '"", "Vigo"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://gdgvigo.typeform.com/to/JvDH2h", text: "Become a speaker"}
 - {link: "https://gdgvigo.typeform.com/to/Tx9PPS", text: "Sponsor us!"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "gdg-devfest.png", text: "GDG DevFests are large, community-run events that can offer speaker sessions across multiple product areas. Awesome speakers and lots of fun!" }

# Statistic Block
statisticBlockImage: "numbers-front.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees"}
 - {count: "8", specialCharacter: "+", info: "hours"}
 - {count: "6", specialCharacter: "+", info: "speakers"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Conference Hall"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "22 Teatral'na St"
eventAddressLocality: "Vigo"
eventAddressLocalityRegion: "Pontevedra"
eventPostalCode: "36202"
eventAddressCountry: "Ukraine"
eventStartTime: "2014-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "42.240065, -8.720963"
mapCenterCoordinates: "42.240065, -8.720963"
mapMobileCenterCoordinates: "42.240065, -8.720963"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"

# Tickets Block
ticketsTitle: "Sponsorships"
ticketsOffers:
 -
  name: "Shy guy"
  price: "150"
  priceCurrency: "€"
  ticketsNumber: "150"
  buyButtonLink: "https://gdgvigo.typeform.com/to/Tx9PPS"
  buyButtonText: "Sponsor Now"
  ticketContentList: ["Logo en web", "Diapositiva conjunta", "Mención en social media"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Big boss"
  price: "800"
  priceCurrency: "€"
  ticketsNumber: "800"
  featured: true
  buyButtonLink: "https://gdgvigo.typeform.com/to/Tx9PPS"
  buyButtonText: "Sponsor Now"
  ticketContentList: ["All from High five ", "Logo en los títulos de la grabación", "Booth para contratar gente"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
 -
  name: "High five"
  price: "400"
  priceCurrency: "€"
  ticketsNumber: "400"
  buyButtonLink: "https://gdgvigo.typeform.com/to/Tx9PPS"
  buyButtonText: "Sponsor Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["All from Shy guy", "Diapositiva propia", "Logo en Camisetas"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"


# Footer
socialLinks:
 - {link: "https://plus.google.com/communities/104458805154699272096", icon: "google-plus"}
 - {link: "https://twitter.com/gdgvigo", icon: "twitter"}
 - {link: "https://www.facebook.com/pg/googledevelopergroupvigo/about/", icon: "facebook"}
 - {link: "https://github.com/GDGVigo", icon: "github"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@gdgvigo.com", text: "info@gdgvigo.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfest"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "We are a team of 5 GDG organisers, each one with our own speciality. We love what we do for the community: help people, meet people and organise events. We are looking forward to meeting you so if you see any one of us and feel like a chat, just stop us and say hi!"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "42.240065, -8.720963"
logisticsMapMobileCenterCoordinates: "42.240065, -8.720963"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
#directionDetailsImage: "direction-details.jpg"
#directionDetailsTitle: "Get around Lviv"

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Vigo"
hackathonAddressLocalityRegion: "Vigo"
hackathonPostalCode: ""
hackathonAddressCountry: "Spain"
hackathonTimeTitle: "Firebase Appfest"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "42.240065, -8.720963"
hackathonMapCenterCoordinates: "42.240065, -8.720963"
hackathonMapMobileCenterCoordinates: "42.240065, -8.720963"
